name: Create Azure Resource Group

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

env:
  DEV_RESOURCE_GROUP_NAME: rg-cloud-pharamcy-dev
  ENVIRONMENT_TYPE: dev

jobs:
  create-resource-group-for-dev-environment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v2
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create development resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.31.0
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az group create --location northeurope --name ${{ env.DEV_RESOURCE_GROUP_NAME }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --tags environment=${{ env.ENVIRONMENT_TYPE }}